[build-system]
requires = ["scikit-build-core>=0.11", "pybind11>=3.0"]
build-backend = "scikit_build_core.build"

[project]
name = "raven_bmi_sys"
version = "0.0.1"

[tool.scikit-build]
sdist.exclude = ["benchmarking", "RavenCaller", ".cache", ".github", "compile_commands.json"]

[tool.scikit-build.cmake.define]
PYTHON = true
COMPILE_LIB = true
COMPILE_EXE = false
