[build-system]
requires = ["scikit-build-core>=0.11", "pybind11>=3.0"]
build-backend = "scikit_build_core.build"

[project]
name = "raven_bmi_sys"
dynamic = ["version"]

[tool.scikit-build]
sdist.exclude = ["benchmarking", "RavenCaller", ".cache", ".github", "compile_commands.json"]

[[tool.dynamic-metadata]]
provider = "scikit_build_core.metadata.regex"
field = "version"
input = "python/raven_bmi_sys/__init__.py"


[tool.scikit-build.cmake.define]
PYTHON = true
COMPILE_STATIC_LIB = true
COMPILE_EXE = false
